"""
Stage 3: Compare (The AI Agent) - using Groq
"""

import argparse
import json
import os
import re
import sys
import time
from collections import defaultdict
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
GUIDELINES_PATH = DATA_DIR / "guidelines_rules.json"
UI_STATE_PATH = DATA_DIR / "ui_states" / "extracted_ui_state.jsonl"
DISCREPANCIES_PATH = DATA_DIR / "discrepancies.json"

DISCLAIMER = (
    "This is an automated compliance check generated by an LLM-based agent. "
    "It is NOT a substitute for manual QA review. Findings should be "
    "verified by a human before being treated as authoritative."
)

MODEL_NAME = "llama-3.1-8b-instant"


def load_guidelines():
    if not GUIDELINES_PATH.exists():
        print(f"[ERROR] {GUIDELINES_PATH} not found. Run Stage 1 first.")
        sys.exit(1)
    with open(GUIDELINES_PATH, encoding="utf-8") as f:
        return json.load(f)


def load_ui_components():
    if not UI_STATE_PATH.exists():
        print(f"[ERROR] {UI_STATE_PATH} not found. Run Stage 2 first.")
        sys.exit(1)
    components = []
    with open(UI_STATE_PATH, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                components.append(json.loads(line))
    return components


def group_components_by_page(components):
    by_page = defaultdict(list)
    for c in components:
        by_page[c["page_url"]].append(c)
    return by_page


def get_llm_client():
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        return None
    from groq import Groq
    return Groq(api_key=api_key)


def call_llm(client, prompt):
    response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[{"role": "user", "content": prompt}],
        temperature=0,
    )
    return response.choices[0].message.content


def page_text_summary(components, max_chars=4000):
    lines = []
    for c in components:
        if c.get("actual_text_content"):
            lines.append(f"[{c['component_type']}] {c['actual_text_content']}")
    return "\n".join(lines)[:max_chars]


def compare_rule_against_page(client, rule, page_url, page_text, components):
    prompt = f"""You are a compliance-checking assistant comparing a live web
application's actual rendered content against a written guideline rule.

GUIDELINE RULE (from {rule['guideline_reference']}):
"{rule['rule_text']}"

ACTUAL PAGE CONTENT (page: {page_url}):
{page_text if page_text else "(no text content extracted for this page)"}

Determine if this guideline rule is clearly violated by the actual page
content above. Only flag a discrepancy if you have clear textual evidence
of a mismatch. Do NOT flag a discrepancy just because the rule isn't
mentioned on this page.

Respond with ONLY a JSON object, no markdown, in this exact shape:
{{
  "applies_to_this_page": true or false,
  "discrepancy_flag": true or false,
  "expected_text_content": "<short excerpt, or null>",
  "actual_text_content": "<short excerpt, or null>",
  "discrepancy_reason": "<one sentence, or null>"
}}
"""
    try:
        raw = call_llm(client, prompt).strip()
        raw = re.sub(r"^```json\s*|\s*```$", "", raw, flags=re.MULTILINE).strip()
        result = json.loads(raw)
    except Exception as e:
        print(f"[WARNING] LLM comparison failed for {rule['rule_id']} on {page_url}: {e}")
        return None

    if not result.get("applies_to_this_page") or not result.get("discrepancy_flag"):
        return None

    screenshot_path = None
    for c in components:
        if c.get("screenshot_path"):
            screenshot_path = c["screenshot_path"]
            break

    return {
        "page_url": page_url,
        "component_type": "text_block",
        "component_selector": None,
        "actual_text_content": result.get("actual_text_content"),
        "expected_text_content": result.get("expected_text_content"),
        "guideline_reference": rule["guideline_reference"],
        "discrepancy_flag": True,
        "discrepancy_reason": result.get("discrepancy_reason"),
        "screenshot_path": screenshot_path,
        "rule_id": rule["rule_id"],
    }


def run_batch_comparison():
    guidelines = load_guidelines()
    components = load_ui_components()
    by_page = group_components_by_page(components)

    client = get_llm_client()
    if client is None:
        print("[ERROR] GROQ_API_KEY not set.")
        sys.exit(1)

    discrepancies = []
    rules = guidelines["rules"]
    total_checks = len(rules) * len(by_page)
    checked = 0

    print(f"[INFO] Comparing {len(rules)} rules against {len(by_page)} pages ({total_checks} checks)")

    for rule in rules:
        for page_url, page_components in by_page.items():
            checked += 1
            text = page_text_summary(page_components)
            result = compare_rule_against_page(client, rule, page_url, text, page_components)
            if result:
                discrepancies.append(result)
                print(f"[FLAGGED] {rule['rule_id']} on {page_url}: {result['discrepancy_reason']}")
            if checked % 20 == 0:
                print(f"[INFO] Progress: {checked}/{total_checks}")
            time.sleep(0.3)

    output = {
        "disclaimer": DISCLAIMER,
        "total_rules_checked": len(rules),
        "total_pages_checked": len(by_page),
        "total_discrepancies_found": len(discrepancies),
        "discrepancies": discrepancies,
    }

    with open(DISCREPANCIES_PATH, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2)

    print(f"[INFO] Found {len(discrepancies)} discrepancies. Saved to {DISCREPANCIES_PATH}")


def run_query_mode(question: str):
    guidelines = load_guidelines()
    components = load_ui_components()
    by_page = group_components_by_page(components)

    client = get_llm_client()
    if client is None:
        print("[ERROR] GROQ_API_KEY not set.")
        sys.exit(1)

    sections_text = "\n\n".join(f"{s['reference']}:\n{s['raw_text']}" for s in guidelines["sections"])
    pages_text = "\n\n".join(
        f"PAGE: {url}\n{page_text_summary(comps, max_chars=1500)}" for url, comps in by_page.items()
    )

    prompt = f"""You are a compliance assistant for the WaiverPro application.
Answer using ONLY the guideline sections and live page content below.
Cite the specific guideline section for every claim. If you cannot answer
from the provided content, say so explicitly.

GUIDELINE SECTIONS:
{sections_text}

LIVE PAGE CONTENT:
{pages_text}

QUESTION: {question}

End your answer with this exact disclaimer on its own line:
"{DISCLAIMER}"
"""
    print("\n" + call_llm(client, prompt))


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--ask", type=str)
    args = parser.parse_args()

    if args.ask:
        run_query_mode(args.ask)
    else:
        run_batch_comparison()